import { AsyncPipe } from '@angular/common';
import { ChangeDetectionStrategy, Component, inject } from '@angular/core';
import { ActivatedRoute } from '@angular/router';
import { Observable, switchMap } from 'rxjs';

import { TMDBMovieModel } from '../../shared/model/movie.model';
import { MovieService } from '../movie.service';
import { MovieListComponent } from '../movie-list/movie-list.component';

@Component({
  selector: 'movie-search-page',
  template: `
    @if (movies$ | async; as movies) {
      @defer (on viewport) {
        <movie-list [movies]="movies" />
      } @placeholder {
        <div class="loader"></div>
      }
    }
  `,
  imports: [MovieListComponent, AsyncPipe],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class MovieSearchPageComponent {
  private movieService = inject(MovieService);
  private activatedRoute = inject(ActivatedRoute);
  private bloat = BLOAT_DATA;
  movies$: Observable<TMDBMovieModel[]> = this.activatedRoute.params.pipe(
    switchMap((params) => this.movieService.searchMovies(params['query'])),
  );
}

// Large JSON object for bloat (~30KB)
export const BLOAT_DATA = {
  movies: [
    {
      id: 1,
      title: 'The Shawshank Redemption',
      overview:
        'Framed in the 1940s for the double murder of his wife and her lover, upstanding banker Andy Dufresne begins a new life at the Shawshank prison, where he puts his accounting skills to work for an amoral warden. During his long stretch in prison, Dufresne comes to be admired by the other inmates -- including an older prisoner named Red -- for his integrity and unquenchable sense of hope.',
      release_date: '1994-09-23',
      vote_average: 8.7,
      vote_count: 26324,
      popularity: 123.456,
      poster_path: '/q6y0Go1tsGEsmtFryDOJo3dEmqu.jpg',
      backdrop_path: '/iNh3BivHyg5sQRPP1KOkzguEX0H.jpg',
      genre_ids: [18, 80],
      adult: false,
      video: false,
      original_language: 'en',
      original_title: 'The Shawshank Redemption',
      cast: [
        {
          id: 1,
          name: 'Tim Robbins',
          character: 'Andy Dufresne',
          profile_path: '/hsCu1JUzQQ4pl7uFxAVFJrsNJjI.jpg',
        },
        {
          id: 2,
          name: 'Morgan Freeman',
          character: "Ellis Boyd 'Red' Redding",
          profile_path: '/905k0RFzH0Kd6TNXjcTaE2XaOw.jpg',
        },
        {
          id: 3,
          name: 'Bob Gunton',
          character: 'Warden Norton',
          profile_path: '/bfCR4uguTKEfWGu5eWuQsyWLgBx.jpg',
        },
      ],
      crew: [
        {
          id: 4,
          name: 'Frank Darabont',
          job: 'Director',
          profile_path: '/7LqmE3p1XTwCdNCOmBxovq210Qk.jpg',
        },
        {
          id: 5,
          name: 'Stephen King',
          job: 'Novel',
          profile_path: '/7LqmE3p1XTwCdNCOmBxovq210Qk.jpg',
        },
      ],
      production_companies: [
        {
          id: 97,
          name: 'Castle Rock Entertainment',
          logo_path: '/7znWcbDd4PcJzJUlSxXqpXrdAXC.png',
        },
        {
          id: 174,
          name: 'Columbia Pictures',
          logo_path: '/IuAlhI9eVC9Z8UQWOIDdWRKSEJ.png',
        },
      ],
      production_countries: [
        { iso_3166_1: 'US', name: 'United States of America' },
      ],
      spoken_languages: [{ iso_639_1: 'en', name: 'English' }],
      keywords: [
        'prison',
        'friendship',
        'hope',
        'corruption',
        'redemption',
        'based on novel',
        'wrongful imprisonment',
      ],
    },
    {
      id: 2,
      title: 'The Godfather',
      overview:
        'Spanning the years 1945 to 1955, a chronicle of the fictional Italian-American Corleone crime family. When organized crime family patriarch, Vito Corleone barely survives an attempt on his life, his youngest son, Michael steps in to take care of the would-be killers, launching a campaign of bloody revenge.',
      release_date: '1972-03-14',
      vote_average: 8.7,
      vote_count: 19858,
      popularity: 149.789,
      poster_path: '/3bhkrj58Vtu7enYsRolD1fZdja1.jpg',
      backdrop_path: '/tmU7GeKVybMWFButWEGl2M4GeiP.jpg',
      genre_ids: [18, 80],
      adult: false,
      video: false,
      original_language: 'en',
      original_title: 'The Godfather',
      cast: [
        {
          id: 6,
          name: 'Marlon Brando',
          character: 'Don Vito Corleone',
          profile_path: '/fuTEPWdcYcfKrusLXV1PyqJdqKh.jpg',
        },
        {
          id: 7,
          name: 'Al Pacino',
          character: 'Michael Corleone',
          profile_path: '/2dGBb1fOcNdZjtQToVPFxXjm4ke.jpg',
        },
        {
          id: 8,
          name: 'James Caan',
          character: 'Sonny Corleone',
          profile_path: '/2dGBb1fOcNdZjtQToVPFxXjm4ke.jpg',
        },
      ],
      crew: [
        {
          id: 9,
          name: 'Francis Ford Coppola',
          job: 'Director',
          profile_path: '/3Pblihd6KjXliie9vj4iQJwbNQI.jpg',
        },
        {
          id: 10,
          name: 'Mario Puzo',
          job: 'Novel',
          profile_path: '/3Pblihd6KjXliie9vj4iQJwbNQI.jpg',
        },
      ],
      production_companies: [
        {
          id: 4,
          name: 'Paramount Pictures',
          logo_path: '/fycMZt242LVjagMByZOLUGbCvv3.png',
        },
        { id: 10, name: 'Alfran Productions', logo_path: null },
      ],
      production_countries: [
        { iso_3166_1: 'US', name: 'United States of America' },
      ],
      spoken_languages: [
        { iso_639_1: 'en', name: 'English' },
        { iso_639_1: 'it', name: 'Italiano' },
      ],
      keywords: [
        'mafia',
        'crime family',
        'violence',
        'loyalty',
        'power',
        'revenge',
        'italian american',
      ],
    },
    {
      id: 3,
      title: 'The Dark Knight',
      overview:
        'Batman raises the stakes in his war on crime. With the help of Lt. Jim Gordon and District Attorney Harvey Dent, Batman sets out to dismantle the remaining criminal organizations that plague the streets. The partnership proves to be effective, but they soon find themselves prey to a reign of chaos unleashed by a rising criminal mastermind known to the terrified citizens of Gotham as the Joker.',
      release_date: '2008-07-18',
      vote_average: 8.5,
      vote_count: 32413,
      popularity: 98.765,
      poster_path: '/qJ2tW6WMUDux911r6m7haRef0WH.jpg',
      backdrop_path: '/hqkIcbrOHL86UncnHIsHVcVmzue.jpg',
      genre_ids: [28, 80, 18, 53],
      adult: false,
      video: false,
      original_language: 'en',
      original_title: 'The Dark Knight',
      cast: [
        {
          id: 11,
          name: 'Christian Bale',
          character: 'Bruce Wayne / Batman',
          profile_path: '/3qx2QFUbG6t6IlzR0F9k3Z6Yhf7.jpg',
        },
        {
          id: 12,
          name: 'Heath Ledger',
          character: 'Joker',
          profile_path: '/5Y9HnYYa9jF4NunY9lSgJGjSe8E.jpg',
        },
        {
          id: 13,
          name: 'Aaron Eckhart',
          character: 'Harvey Dent / Two-Face',
          profile_path: '/3qx2QFUbG6t6IlzR0F9k3Z6Yhf7.jpg',
        },
      ],
      crew: [
        {
          id: 14,
          name: 'Christopher Nolan',
          job: 'Director',
          profile_path: '/xuAIuYSmsUzKlUMBFGVZaWsY3DZ.jpg',
        },
        {
          id: 15,
          name: 'Jonathan Nolan',
          job: 'Screenplay',
          profile_path: '/xuAIuYSmsUzKlUMBFGVZaWsY3DZ.jpg',
        },
      ],
      production_companies: [
        {
          id: 9996,
          name: 'Warner Bros. Pictures',
          logo_path: '/IuAlhI9eVC9Z8UQWOIDdWRKSEJ.png',
        },
        {
          id: 9999,
          name: 'Legendary Entertainment',
          logo_path: '/IuAlhI9eVC9Z8UQWOIDdWRKSEJ.png',
        },
      ],
      production_countries: [
        { iso_3166_1: 'US', name: 'United States of America' },
        { iso_3166_1: 'GB', name: 'United Kingdom' },
      ],
      spoken_languages: [{ iso_639_1: 'en', name: 'English' }],
      keywords: [
        'superhero',
        'batman',
        'joker',
        'gotham city',
        'vigilante',
        'chaos',
        'crime fighting',
        'moral dilemma',
      ],
    },
    {
      id: 4,
      title: 'Pulp Fiction',
      overview:
        "A burger-loving hit man, his philosophical partner, a drug-addled gangster's moll and a washed-up boxer converge in this sprawling, comedic crime caper. Their adventures unfurl in three stories that ingeniously trip back and forth in time.",
      release_date: '1994-09-10',
      vote_average: 8.5,
      vote_count: 27847,
      popularity: 87.432,
      poster_path: '/d5iIlFn5s0ImszYzBPb8JPIfbXD.jpg',
      backdrop_path: '/4cDFJr4HnXN5AdPw4AKrmLlMWdO.jpg',
      genre_ids: [53, 80],
      adult: false,
      video: false,
      original_language: 'en',
      original_title: 'Pulp Fiction',
      cast: [
        {
          id: 16,
          name: 'John Travolta',
          character: 'Vincent Vega',
          profile_path: '/yYhwWRcxDHTn63gSEF1vnDAD7cD.jpg',
        },
        {
          id: 17,
          name: 'Samuel L. Jackson',
          character: 'Jules Winnfield',
          profile_path: '/AiAYAqwpM5xmiFrAIeQvUXDCVvo.jpg',
        },
        {
          id: 18,
          name: 'Uma Thurman',
          character: 'Mia Wallace',
          profile_path: '/xuxgPXyv6KjUHIM8cZaxx4ry25L.jpg',
        },
      ],
      crew: [
        {
          id: 19,
          name: 'Quentin Tarantino',
          job: 'Director',
          profile_path: '/1gjcpAa99FAOWGnrUvHEXXsRs7o.jpg',
        },
        {
          id: 20,
          name: 'Roger Avary',
          job: 'Screenplay',
          profile_path: '/1gjcpAa99FAOWGnrUvHEXXsRs7o.jpg',
        },
      ],
      production_companies: [
        {
          id: 14,
          name: 'Miramax',
          logo_path: '/m6AHu84oZQxvq9Pz8lWXTqPf7wn.png',
        },
        { id: 15, name: 'A Band Apart', logo_path: null },
      ],
      production_countries: [
        { iso_3166_1: 'US', name: 'United States of America' },
      ],
      spoken_languages: [
        { iso_639_1: 'en', name: 'English' },
        { iso_639_1: 'es', name: 'Español' },
        { iso_639_1: 'fr', name: 'Français' },
      ],
      keywords: [
        'nonlinear timeline',
        'hitman',
        'crime',
        'violence',
        'dialogue',
        'pop culture',
        'los angeles',
        'anthology',
      ],
    },
    {
      id: 5,
      title: "Schindler's List",
      overview:
        'The true story of how businessman Oskar Schindler saved over a thousand Jewish lives from the Nazis while they worked as slaves in his factory during World War II.',
      release_date: '1993-12-15',
      vote_average: 8.6,
      vote_count: 15127,
      popularity: 76.543,
      poster_path: '/sF1U4EUQS8YHUYjNl3pMGNIQyr0.jpg',
      backdrop_path: '/loRmRzQXZeqG78TqZuyvSlEQfZb.jpg',
      genre_ids: [18, 36, 10752],
      adult: false,
      video: false,
      original_language: 'en',
      original_title: "Schindler's List",
      cast: [
        {
          id: 21,
          name: 'Liam Neeson',
          character: 'Oskar Schindler',
          profile_path: '/bboldwqSC6tdw2iL6631c98l2Mn.jpg',
        },
        {
          id: 22,
          name: 'Ben Kingsley',
          character: 'Itzhak Stern',
          profile_path: '/vQtBqpF2HDdzbfXHDzR4u37i1Ac.jpg',
        },
        {
          id: 23,
          name: 'Ralph Fiennes',
          character: 'Amon Göth',
          profile_path: '/tJr9GcmGNHhLVVEH3i7QYbj6hBi.jpg',
        },
      ],
      crew: [
        {
          id: 24,
          name: 'Steven Spielberg',
          job: 'Director',
          profile_path: '/tZxcg19YQ3e8fJ0pOs7hjlnmmr6.jpg',
        },
        {
          id: 25,
          name: 'Steven Zaillian',
          job: 'Screenplay',
          profile_path: '/tZxcg19YQ3e8fJ0pOs7hjlnmmr6.jpg',
        },
      ],
      production_companies: [
        {
          id: 56,
          name: 'Universal Pictures',
          logo_path: '/o86DbpburjxrqAzEDhXZcyE8pDb.png',
        },
        {
          id: 57,
          name: 'Amblin Entertainment',
          logo_path: '/vPWqVflqLlgqVcOy2oHWknKTIhB.png',
        },
      ],
      production_countries: [
        { iso_3166_1: 'US', name: 'United States of America' },
      ],
      spoken_languages: [
        { iso_639_1: 'en', name: 'English' },
        { iso_639_1: 'he', name: 'עברית' },
        { iso_639_1: 'de', name: 'Deutsch' },
        { iso_639_1: 'pl', name: 'Polski' },
      ],
      keywords: [
        'holocaust',
        'world war ii',
        'nazi',
        'factory',
        'jews',
        'salvation',
        'historical',
        'biography',
      ],
    },
    {
      id: 6,
      title: 'The Lord of the Rings: The Return of the King',
      overview:
        "Aragorn is revealed as the heir to the ancient kings as he, Gandalf and the other members of the broken fellowship struggle to save Gondor from Sauron's forces. Meanwhile, Frodo and Sam take the ring closer to the heart of Mordor, the dark lord's realm.",
      release_date: '2003-12-01',
      vote_average: 8.5,
      vote_count: 23681,
      popularity: 145.678,
      poster_path: '/rCzpDGLbOoPwLjy3OAm5NUPOTrC.jpg',
      backdrop_path: '/2u7zbn8EudG6kLlBzUYqP8RyFU4.jpg',
      genre_ids: [12, 18, 14],
      adult: false,
      video: false,
      original_language: 'en',
      original_title: 'The Lord of the Rings: The Return of the King',
      cast: [
        {
          id: 26,
          name: 'Elijah Wood',
          character: 'Frodo Baggins',
          profile_path: '/7UKRbJBNG7mxBl2QQc5XsAh6F8B.jpg',
        },
        {
          id: 27,
          name: 'Ian McKellen',
          character: 'Gandalf',
          profile_path: '/coJjatYWnDNuJuAsCdWKJOCM8St.jpg',
        },
        {
          id: 28,
          name: 'Viggo Mortensen',
          character: 'Aragorn',
          profile_path: '/vH5gVSpHAMhDaFWfh0Q7BG61O1y.jpg',
        },
      ],
      crew: [
        {
          id: 29,
          name: 'Peter Jackson',
          job: 'Director',
          profile_path: '/bNc908d59Ba8VDNr4eCcm4G1cR.jpg',
        },
        {
          id: 30,
          name: 'J.R.R. Tolkien',
          job: 'Novel',
          profile_path: '/bNc908d59Ba8VDNr4eCcm4G1cR.jpg',
        },
      ],
      production_companies: [
        {
          id: 12,
          name: 'New Line Cinema',
          logo_path: '/aOWKh4gkNrfFZ3Ep7n0ckPhoGb8.png',
        },
        {
          id: 13,
          name: 'WingNut Films',
          logo_path: '/aOWKh4gkNrfFZ3Ep7n0ckPhoGb8.png',
        },
      ],
      production_countries: [
        { iso_3166_1: 'NZ', name: 'New Zealand' },
        { iso_3166_1: 'US', name: 'United States of America' },
      ],
      spoken_languages: [{ iso_639_1: 'en', name: 'English' }],
      keywords: [
        'epic',
        'fantasy',
        'adventure',
        'middle earth',
        'ring',
        'quest',
        'friendship',
        'sacrifice',
        'good vs evil',
      ],
    },
    {
      id: 7,
      title: 'Goodfellas',
      overview:
        'The true story of Henry Hill, a half-Irish, half-Sicilian Brooklyn kid who is adopted by neighbourhood gangsters at an early age and climbs the ranks of a Mafia family under the guidance of Jimmy Conway.',
      release_date: '1990-09-12',
      vote_average: 8.5,
      vote_count: 12456,
      popularity: 89.123,
      poster_path: '/aKuFiU82s5ISJpGZp7YkIr3kCUd.jpg',
      backdrop_path: '/sw7mordbZxgITU877yTpZCud90M.jpg',
      genre_ids: [18, 80],
      adult: false,
      video: false,
      original_language: 'en',
      original_title: 'Goodfellas',
      cast: [
        {
          id: 31,
          name: 'Robert De Niro',
          character: 'James Conway',
          profile_path: '/cT8htcckIuyI1Lqwt1CvD02ynTh.jpg',
        },
        {
          id: 32,
          name: 'Ray Liotta',
          character: 'Henry Hill',
          profile_path: '/vvNqbdXfmOPRmg26yB6kcLKJsGj.jpg',
        },
        {
          id: 33,
          name: 'Joe Pesci',
          character: 'Tommy DeVito',
          profile_path: '/bWNgJMVoOjWJbOKGhbOcmN3hLvG.jpg',
        },
      ],
      crew: [
        {
          id: 34,
          name: 'Martin Scorsese',
          job: 'Director',
          profile_path: '/52dXGVGUsOKWWJHnNqyNNONkqfL.jpg',
        },
        {
          id: 35,
          name: 'Nicholas Pileggi',
          job: 'Screenplay',
          profile_path: '/52dXGVGUsOKWWJHnNqyNNONkqfL.jpg',
        },
      ],
      production_companies: [
        {
          id: 9996,
          name: 'Warner Bros. Pictures',
          logo_path: '/IuAlhI9eVC9Z8UQWOIDdWRKSEJ.png',
        },
      ],
      production_countries: [
        { iso_3166_1: 'US', name: 'United States of America' },
      ],
      spoken_languages: [
        { iso_639_1: 'en', name: 'English' },
        { iso_639_1: 'it', name: 'Italiano' },
      ],
      keywords: [
        'mafia',
        'organized crime',
        'true story',
        'violence',
        'loyalty',
        'betrayal',
        'new york',
        'gangster',
      ],
    },
    {
      id: 8,
      title: 'Fight Club',
      overview:
        'A ticking-time-bomb insomniac and a slippery soap salesman channel primal male aggression into a shocking new form of therapy. Their concept catches on, with underground "fight clubs" forming in every town, until an eccentric gets in the way and ignites an out-of-control spiral toward oblivion.',
      release_date: '1999-10-15',
      vote_average: 8.4,
      vote_count: 26789,
      popularity: 134.567,
      poster_path: '/pB8BM7pdSp6B6Ih7QZ4DrQ3PmJK.jpg',
      backdrop_path: '/hZkgoQYus5vegHoetLkCJzb17zJ.jpg',
      genre_ids: [18],
      adult: false,
      video: false,
      original_language: 'en',
      original_title: 'Fight Club',
      cast: [
        {
          id: 36,
          name: 'Brad Pitt',
          character: 'Tyler Durden',
          profile_path: '/cckcYc2v0yh1tc9QjRelptcOBko.jpg',
        },
        {
          id: 37,
          name: 'Edward Norton',
          character: 'The Narrator',
          profile_path: '/5XBzD5WuTyVQZeS4VI25z2moMeY.jpg',
        },
        {
          id: 38,
          name: 'Helena Bonham Carter',
          character: 'Marla Singer',
          profile_path: '/DDeITcCpnBd0CkAIRPhggy9bt5.jpg',
        },
      ],
      crew: [
        {
          id: 39,
          name: 'David Fincher',
          job: 'Director',
          profile_path: '/dcBHejOsKvzVZVozWJAPzYthb8X.jpg',
        },
        {
          id: 40,
          name: 'Chuck Palahniuk',
          job: 'Novel',
          profile_path: '/dcBHejOsKvzVZVozWJAPzYthb8X.jpg',
        },
      ],
      production_companies: [
        {
          id: 25,
          name: '20th Century Fox',
          logo_path: '/qZCc1lty5FzX30aOCVRBLzaVmcp.png',
        },
        {
          id: 26,
          name: 'Fox 2000 Pictures',
          logo_path: '/qZCc1lty5FzX30aOCVRBLzaVmcp.png',
        },
      ],
      production_countries: [
        { iso_3166_1: 'US', name: 'United States of America' },
      ],
      spoken_languages: [{ iso_639_1: 'en', name: 'English' }],
      keywords: [
        'insomnia',
        'masculinity',
        'consumerism',
        'identity',
        'violence',
        'underground',
        'philosophy',
        'twist ending',
      ],
    },
    {
      id: 9,
      title: 'Forrest Gump',
      overview:
        'A man with a low IQ has accomplished great things in his life and been present during significant historic events—in each case, far exceeding what anyone imagined he could do. But despite all he has achieved, his one true love eludes him.',
      release_date: '1994-06-23',
      vote_average: 8.5,
      vote_count: 26472,
      popularity: 98.765,
      poster_path: '/arw2vcBveWOVZr6pxd9XTd1TdQa.jpg',
      backdrop_path: '/3h1JZGDhZ8nzxdgvkxha0qBqi05.jpg',
      genre_ids: [35, 18, 10749],
      adult: false,
      video: false,
      original_language: 'en',
      original_title: 'Forrest Gump',
      cast: [
        {
          id: 41,
          name: 'Tom Hanks',
          character: 'Forrest Gump',
          profile_path: '/xndWFsBlClOJFRdhSt4NBwiPq2o.jpg',
        },
        {
          id: 42,
          name: 'Robin Wright',
          character: 'Jenny Curran',
          profile_path: '/9Pk6cSPVtKIGnCXzxfF6YqhHKBH.jpg',
        },
        {
          id: 43,
          name: 'Gary Sinise',
          character: 'Lieutenant Dan Taylor',
          profile_path: '/8Uh1aXxaIjhA1ScUKHWZHSVZk9V.jpg',
        },
      ],
      crew: [
        {
          id: 44,
          name: 'Robert Zemeckis',
          job: 'Director',
          profile_path: '/lPYDQ5LYNJ12rJZENtyASmVZ1Ql.jpg',
        },
        {
          id: 45,
          name: 'Eric Roth',
          job: 'Screenplay',
          profile_path: '/lPYDQ5LYNJ12rJZENtyASmVZ1Ql.jpg',
        },
      ],
      production_companies: [
        {
          id: 4,
          name: 'Paramount Pictures',
          logo_path: '/fycMZt242LVjagMByZOLUGbCvv3.png',
        },
      ],
      production_countries: [
        { iso_3166_1: 'US', name: 'United States of America' },
      ],
      spoken_languages: [{ iso_639_1: 'en', name: 'English' }],
      keywords: [
        'vietnam war',
        'disability',
        'friendship',
        'love',
        'american history',
        'running',
        'shrimp',
        'chocolate',
      ],
    },
    {
      id: 10,
      title: 'Inception',
      overview:
        'Cobb, a skilled thief who commits corporate espionage by infiltrating the subconscious of his targets is offered a chance to regain his old life as payment for a task considered to be impossible: "inception", the implantation of another person\'s idea into a target\'s subconscious.',
      release_date: '2010-07-15',
      vote_average: 8.4,
      vote_count: 35789,
      popularity: 156.789,
      poster_path: '/9gk7adHYeDvHkCSEqAvQNLV5Uge.jpg',
      backdrop_path: '/s3TBrRGB1iav7gFOCNx3H31MoES.jpg',
      genre_ids: [28, 878, 53],
      adult: false,
      video: false,
      original_language: 'en',
      original_title: 'Inception',
      cast: [
        {
          id: 46,
          name: 'Leonardo DiCaprio',
          character: 'Dom Cobb',
          profile_path: '/wo2hJpn04vbtmh0B9utCFdsQhxM.jpg',
        },
        {
          id: 47,
          name: 'Marion Cotillard',
          character: 'Mal',
          profile_path: '/b4tXjHGgj1CqXrmZzyw5a1aW8Pu.jpg',
        },
        {
          id: 48,
          name: 'Tom Hardy',
          character: 'Eames',
          profile_path: '/d81K0RH8UX7tZj49tZaQhZ9ewH.jpg',
        },
      ],
      crew: [
        {
          id: 14,
          name: 'Christopher Nolan',
          job: 'Director',
          profile_path: '/xuAIuYSmsUzKlUMBFGVZaWsY3DZ.jpg',
        },
        {
          id: 49,
          name: 'Emma Thomas',
          job: 'Producer',
          profile_path: '/xuAIuYSmsUzKlUMBFGVZaWsY3DZ.jpg',
        },
      ],
      production_companies: [
        {
          id: 9996,
          name: 'Warner Bros. Pictures',
          logo_path: '/IuAlhI9eVC9Z8UQWOIDdWRKSEJ.png',
        },
        {
          id: 9999,
          name: 'Legendary Entertainment',
          logo_path: '/IuAlhI9eVC9Z8UQWOIDdWRKSEJ.png',
        },
      ],
      production_countries: [
        { iso_3166_1: 'US', name: 'United States of America' },
        { iso_3166_1: 'GB', name: 'United Kingdom' },
      ],
      spoken_languages: [
        { iso_639_1: 'en', name: 'English' },
        { iso_639_1: 'ja', name: '日本語' },
        { iso_639_1: 'fr', name: 'Français' },
      ],
      keywords: [
        'dreams',
        'subconscious',
        'heist',
        'reality',
        'mind bending',
        'layered narrative',
        'extraction',
        'limbo',
      ],
    },
  ],
  metadata: {
    total_results: 10000,
    total_pages: 500,
    current_page: 1,
    results_per_page: 20,
    api_version: '3.0',
    last_updated: '2024-01-15T10:30:00Z',
    cache_expiry: '2024-01-16T10:30:00Z',
    request_id: 'req_12345678901234567890',
    processing_time_ms: 245,
    server_region: 'us-east-1',
    content_rating: 'PG-13',
    language: 'en-US',
    country: 'US',
    timezone: 'UTC',
    user_agent: 'MovieApp/1.0 (Angular 17.0.0)',
    ip_address: '192.168.1.100',
    session_id: 'sess_abcdef123456789',
    user_id: 'user_987654321',
    preferences: {
      adult_content: false,
      include_video: true,
      sort_by: 'popularity.desc',
      primary_release_year: null,
      vote_count_gte: 100,
      vote_average_gte: 6.0,
      with_genres: [],
      without_genres: [99, 10770],
      with_keywords: [],
      without_keywords: [],
      with_companies: [],
      with_people: [],
      certification_country: 'US',
      certification: '',
      certification_lte: '',
      include_adult: false,
      page: 1,
      primary_release_date_gte: null,
      primary_release_date_lte: null,
      release_date_gte: null,
      release_date_lte: null,
      with_release_type: 3,
      year: null,
      without_companies: [],
      with_runtime_gte: null,
      with_runtime_lte: null,
      with_original_language: 'en',
    },
    filters_applied: {
      genre_filter: false,
      year_filter: false,
      rating_filter: true,
      language_filter: true,
      adult_filter: true,
      video_filter: false,
      popularity_filter: false,
      vote_count_filter: true,
      runtime_filter: false,
      certification_filter: false,
      keyword_filter: false,
      company_filter: false,
      person_filter: false,
      release_date_filter: false,
    },
    search_statistics: {
      total_searches_today: 15672,
      unique_users_today: 8934,
      average_response_time_ms: 187,
      cache_hit_rate: 0.78,
      error_rate: 0.002,
      most_searched_terms: [
        'action movies',
        'comedy 2023',
        'marvel',
        'horror',
        'drama',
        'sci-fi',
        'thriller',
        'romance',
        'animation',
        'documentary',
      ],
      trending_genres: [
        { id: 28, name: 'Action', searches: 3456 },
        { id: 35, name: 'Comedy', searches: 2987 },
        { id: 18, name: 'Drama', searches: 2654 },
        { id: 878, name: 'Science Fiction', searches: 2341 },
        { id: 53, name: 'Thriller', searches: 2198 },
      ],
      peak_hours: [
        { hour: 20, searches: 1234 },
        { hour: 21, searches: 1456 },
        { hour: 19, searches: 1123 },
        { hour: 22, searches: 987 },
        { hour: 18, searches: 876 },
      ],
    },
    system_info: {
      database_version: 'PostgreSQL 14.9',
      redis_version: '7.0.12',
      elasticsearch_version: '8.10.2',
      api_gateway_version: '2.15.1',
      load_balancer: 'nginx/1.24.0',
      cdn_provider: 'CloudFlare',
      monitoring: 'DataDog',
      logging: 'ELK Stack',
      container_orchestration: 'Kubernetes 1.28',
      cloud_provider: 'AWS',
      region: 'us-east-1',
      availability_zones: ['us-east-1a', 'us-east-1b', 'us-east-1c'],
      auto_scaling: true,
      backup_strategy: 'daily_snapshots',
      disaster_recovery: 'multi_region',
      security_scanning: 'Snyk',
      ssl_certificate: "Let's Encrypt",
      rate_limiting: 'Redis + Lua',
      caching_strategy: 'multi_layer',
      image_optimization: 'ImageKit',
      video_streaming: 'AWS CloudFront',
    },
  },
  additional_data: {
    genres: [
      { id: 28, name: 'Action' },
      { id: 12, name: 'Adventure' },
      { id: 16, name: 'Animation' },
      { id: 35, name: 'Comedy' },
      { id: 80, name: 'Crime' },
      { id: 99, name: 'Documentary' },
      { id: 18, name: 'Drama' },
      { id: 10751, name: 'Family' },
      { id: 14, name: 'Fantasy' },
      { id: 36, name: 'History' },
      { id: 27, name: 'Horror' },
      { id: 10402, name: 'Music' },
      { id: 9648, name: 'Mystery' },
      { id: 10749, name: 'Romance' },
      { id: 878, name: 'Science Fiction' },
      { id: 10770, name: 'TV Movie' },
      { id: 53, name: 'Thriller' },
      { id: 10752, name: 'War' },
      { id: 37, name: 'Western' },
    ],
    countries: [
      { iso_3166_1: 'US', english_name: 'United States of America' },
      { iso_3166_1: 'GB', english_name: 'United Kingdom' },
      { iso_3166_1: 'FR', english_name: 'France' },
      { iso_3166_1: 'DE', english_name: 'Germany' },
      { iso_3166_1: 'IT', english_name: 'Italy' },
      { iso_3166_1: 'ES', english_name: 'Spain' },
      { iso_3166_1: 'JP', english_name: 'Japan' },
      { iso_3166_1: 'KR', english_name: 'South Korea' },
      { iso_3166_1: 'CN', english_name: 'China' },
      { iso_3166_1: 'IN', english_name: 'India' },
      { iso_3166_1: 'CA', english_name: 'Canada' },
      { iso_3166_1: 'AU', english_name: 'Australia' },
      { iso_3166_1: 'BR', english_name: 'Brazil' },
      { iso_3166_1: 'MX', english_name: 'Mexico' },
      { iso_3166_1: 'RU', english_name: 'Russia' },
      { iso_3166_1: 'NZ', english_name: 'New Zealand' },
      { iso_3166_1: 'SE', english_name: 'Sweden' },
      { iso_3166_1: 'NO', english_name: 'Norway' },
      { iso_3166_1: 'DK', english_name: 'Denmark' },
      { iso_3166_1: 'FI', english_name: 'Finland' },
    ],
    languages: [
      { iso_639_1: 'en', english_name: 'English', name: 'English' },
      { iso_639_1: 'es', english_name: 'Spanish', name: 'Español' },
      { iso_639_1: 'fr', english_name: 'French', name: 'Français' },
      { iso_639_1: 'de', english_name: 'German', name: 'Deutsch' },
      { iso_639_1: 'it', english_name: 'Italian', name: 'Italiano' },
      { iso_639_1: 'pt', english_name: 'Portuguese', name: 'Português' },
      { iso_639_1: 'ja', english_name: 'Japanese', name: '日本語' },
      { iso_639_1: 'ko', english_name: 'Korean', name: '한국어' },
      { iso_639_1: 'zh', english_name: 'Mandarin', name: '普通话' },
      { iso_639_1: 'hi', english_name: 'Hindi', name: 'हिन्दी' },
      { iso_639_1: 'ar', english_name: 'Arabic', name: 'العربية' },
      { iso_639_1: 'ru', english_name: 'Russian', name: 'Pусский' },
      { iso_639_1: 'pl', english_name: 'Polish', name: 'Polski' },
      { iso_639_1: 'nl', english_name: 'Dutch', name: 'Nederlands' },
      { iso_639_1: 'sv', english_name: 'Swedish', name: 'svenska' },
      { iso_639_1: 'da', english_name: 'Danish', name: 'Dansk' },
      { iso_639_1: 'no', english_name: 'Norwegian', name: 'Norsk' },
      { iso_639_1: 'fi', english_name: 'Finnish', name: 'suomi' },
      { iso_639_1: 'he', english_name: 'Hebrew', name: 'עברית' },
      { iso_639_1: 'th', english_name: 'Thai', name: 'ภาษาไทย' },
    ],
    certifications: {
      US: [
        {
          certification: 'G',
          meaning:
            'All ages admitted. Nothing that would offend parents for viewing by children.',
          order: 1,
        },
        {
          certification: 'PG',
          meaning:
            'Some material may not be suitable for children. Parents urged to give "parental guidance". May contain some material parents might not like for their young children.',
          order: 2,
        },
        {
          certification: 'PG-13',
          meaning:
            'Some material may be inappropriate for children under 13. Parents are urged to be cautious. Some material may be inappropriate for pre-teenagers.',
          order: 3,
        },
        {
          certification: 'R',
          meaning:
            'Under 17 requires accompanying parent or adult guardian. Contains some adult material. Parents are urged to learn more about the film before taking their young children with them.',
          order: 4,
        },
        {
          certification: 'NC-17',
          meaning:
            'No One 17 and Under Admitted. Clearly adult. Children are not admitted.',
          order: 5,
        },
      ],
      GB: [
        {
          certification: 'U',
          meaning:
            'All ages admitted, there is nothing unsuitable for children.',
          order: 1,
        },
        {
          certification: 'PG',
          meaning:
            'All ages admitted, but certain scenes may be unsuitable for young children. May contain mild language and sex/drugs references. May contain moderate violence if justified by context.',
          order: 2,
        },
        {
          certification: '12A',
          meaning:
            'Films under this category are considered to be unsuitable for very young people. Those aged under 12 years are only admitted if accompanied by an adult, aged at least 18 years, at all times during the motion picture. However, it is generally not recommended that children under 12 years should watch the film.',
          order: 3,
        },
        {
          certification: '12',
          meaning:
            'Home media only since 2002. 12A-rated films are usually given a 12 certificate for the VHS/DVD version unless extra material has been added that requires a higher rating. Nobody younger than 12 can rent or buy a 12-rated VHS, DVD, Blu-ray Disc, UMD or game.',
          order: 4,
        },
        {
          certification: '15',
          meaning:
            'Only those over 15 years are admitted. Nobody younger than 15 can rent or buy a 15-rated VHS, DVD, Blu-ray Disc, UMD or game, or watch a film in the cinema with this rating. Films under this category can contain adult themes, hard drugs, frequent strong language, moderate-strong violence/sex references, and mild non-detailed sex activity.',
          order: 5,
        },
        {
          certification: '18',
          meaning:
            'Only adults are admitted. Nobody younger than 18 can rent or buy an 18-rated VHS, DVD, Blu-ray Disc, UMD or game, or watch a film in the cinema with this rating. Films under this category do not have limitation on the bad language that is used. Hard drugs are generally allowed, and explicit sex references along with detailed sexual activity are also allowed. Scenes of strong real sex may be permitted if justified by the context. Very strong, gory, and/or sadistic violence is usually permitted. Strong sadistic violence is usually only permitted when mitigated by a strong or developed context.',
          order: 6,
        },
      ],
    },
    popular_keywords: [
      'superhero',
      'based on novel',
      'sequel',
      'friendship',
      'love',
      'revenge',
      'murder',
      'police',
      'family',
      'war',
      'school',
      'hospital',
      'prison',
      'alien',
      'vampire',
      'zombie',
      'robot',
      'time travel',
      'space',
      'magic',
      'dragon',
      'princess',
      'king',
      'queen',
      'knight',
      'sword',
      'castle',
      'treasure',
      'pirate',
      'ship',
      'island',
      'jungle',
      'desert',
      'mountain',
      'city',
      'village',
      'forest',
      'ocean',
      'river',
      'lake',
      'fire',
      'ice',
      'storm',
      'earthquake',
      'volcano',
      'flood',
      'tornado',
      'hurricane',
      'lightning',
      'thunder',
    ],
    trending_people: [
      {
        id: 1,
        name: 'Ryan Reynolds',
        known_for_department: 'Acting',
        popularity: 45.678,
      },
      {
        id: 2,
        name: 'Margot Robbie',
        known_for_department: 'Acting',
        popularity: 43.234,
      },
      {
        id: 3,
        name: 'Dwayne Johnson',
        known_for_department: 'Acting',
        popularity: 41.567,
      },
      {
        id: 4,
        name: 'Emma Stone',
        known_for_department: 'Acting',
        popularity: 39.89,
      },
      {
        id: 5,
        name: 'Chris Evans',
        known_for_department: 'Acting',
        popularity: 38.123,
      },
      {
        id: 6,
        name: 'Scarlett Johansson',
        known_for_department: 'Acting',
        popularity: 36.456,
      },
      {
        id: 7,
        name: 'Robert Downey Jr.',
        known_for_department: 'Acting',
        popularity: 34.789,
      },
      {
        id: 8,
        name: 'Jennifer Lawrence',
        known_for_department: 'Acting',
        popularity: 33.012,
      },
      {
        id: 9,
        name: 'Tom Holland',
        known_for_department: 'Acting',
        popularity: 31.345,
      },
      {
        id: 10,
        name: 'Zendaya',
        known_for_department: 'Acting',
        popularity: 29.678,
      },
    ],
  },
};
